### ISSUE TITLE
SPEC: Develop Network Service Endpoints

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/nsmctl#1]
## Overview

We need to provide a generic way to simplification of developing [Network Service Endpoint](https://networkservicemesh.io/docs/concepts/architecture/#endpoints).

## Link to the Google Docs document

https://docs.google.com/document/d/1rPhmqU71t5YgJQ_mWETtr2q6Z7AMO8e4NrZRvFTmFIU/edit?usp=sharing

**Comment by denis-tingaikin** [comment]
## Subtasks

- [X] Design ~3h
- [X] Cobra integration ~3h
- [X] implement cmd/nsmctl ~3h
- [X] implement cmd/gen ~3h
- [X] implement cmd/gen/endpoint ~3h
- [X] implement cmd/gen/endpoint/vpp ~3h

Total ~18h
